apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: openwhisk-nodejs-runtime-git
spec:
  type: git
  params:
    - name: revision
      value: dockerfile 
    - name: url
      value: https://github.com/pritidesai/incubator-openwhisk-runtime-nodejs.git
