apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: openwhisk-nodejs-runtime-image
spec:
  type: image
  params:
    - name: url
      value: docker.io/pritidesai/openwhisk-nodejs-helloworld
