apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: openwhisk-nodejs-runtime-image
spec:
  serviceAccount: openwhisk-runtime-builder
  type: image
  params:
    - name: url
      value: docker.io/${DOCKERHUB_USERNAME}/openwhisk-nodejs-helloworld
