apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: openwhisk-nodejs-helloworld
spec:
  serviceAccount: openwhisk-runtime-builder
  taskRef:
    name: openwhisk-nodejs-runtime
  trigger:
    type: manual
  inputs:
    resources:
      - name: runtime-git
        resourceRef:
          name: openwhisk-nodejs-runtime-git
    params:
      - name: TARGET_IMAGE_NAME
        value: "docker.io/${DOCKUERHUB_USERNAME}/openwhisk-nodejs-helloworld"
      - name: DOCKERFILE
        value: "./runtime-git/core/nodejs10Action/knative/Dockerfile"
      - name: OW_ACTION_NAME
        value: "nodejs-helloworld"
      - name: OW_ACTION_CODE
        value: "function main() {return {payload: 'Hello World!'};}"
      - name: OW_PROJECT_URL
        value: ""
  outputs:
    resources:
      - name: runtime-image
        resourceRef:
          name: openwhisk-nodejs-runtime-image
