apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
    name: task-with-parameters
spec:
    inputs:
        params:
            - name: var
              type: string
              # default of empty value does not work in this case
              default: "Hello World"
    steps:
        - name: echo
          image: ubuntu
          command:
            - echo
          args:
            - "${inputs.params.var}"
