apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: skaffold-image-leeroy-web
spec:
  serviceAccount: openwhisk-runtime-builder
  type: image
  params:
    - name: url
      value: docker.io/pritidesai/leeroy-web
